# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490a6ebc652069feeefe611b3a7b637ae2c7797c3860e227192b0bdbff9d054e1bc33102304c5b931aa3b18c736d27f7c6e0c564b711a282a07ec3056321617f

test:
  secret_key_base: 3cf7e2105cbbbc47842c1a11f63abb2a148934e48a7b27f251dba71cccb243bc0711ecedb054713a23a31a8df6511e7c9314b200c8038f34fd728296694b8af2

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
